services:
  - type: web
    name: springboot-backend
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    rootDir: .
    envVars:
      - key: PGHOST
        value: shortline.proxy.rlwy.net          # PUBLICZNY adres hosta Railway
      - key: PGPORT
        value: "32783"                            # PUBLICZNY port z DATABASE_PUBLIC_URL
      - key: PGUSER
        value: postgres
      - key: PGPASSWORD
        value: ZtdreJBzZEvwavRTYnJMzTkLUndiovJI   # Hasło z Railway
      - key: PGDATABASE
        value: railway                            # Nazwa bazy (sprawdź w Railway)
      - key: PORT
        value: "8080"                             # Port aplikacji (domyślny Spring Boot)
